
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=69C1500F4BCE663FF955B59071ACC63A

[/Script/GameplayAbilities.AbilitySystemGlobals]
; BARUGame GAS 글로벌 시스템 클래스 및 실패 태그 지정
;AbilitySystemGlobalsClassName=/Script/BARUGame.UBaruAbilitySystemGlobals
ActivateFailCooldownTag=Ability.ActivateFail.Cooldown
ActivateFailCostTag=Ability.ActivateFail.Cost
ActivateFailTagsBlockedTag=Ability.ActivateFail.TagsBlocked

; 프로젝트 전체(/Game/)를 스캔하여 발생하는 성능 저하 경고 제거 (부팅 속도 단축)
+GameplayCueNotifyPaths="/Game/BARUGame"